apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: "https://212.2.243.159:6443"
  project: default
  source:
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    path: apps/civo/nginx-manifests
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true