apiVersion: v1
kind: Pod
metadata:
  name: efk-log-test
  namespace: default
spec:
  containers:
    - name: log-generator
      image: busybox:1.36.1

      command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "$(date -Iseconds) Subaru EFK logging test"
            sleep 10
          done
