apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "temp-deepdive.fullname" . }}
  labels: {{ include "temp-deepdive.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "temp-deepdive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "temp-deepdive.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.mycontainerPort.http }}