{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "temp-deepdive.fullname" . }}
  labels:
    {{- include "temp-deepdive.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "temp-deepdive.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.mycontainerPort.http }}
{{- end }}