apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system2
  name: solar-system2
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system2
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system2
    spec:
      containers:
      - image: siddharth67/solar-system:v9
        name: solar-system2
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
        volumeMounts:
          - name: nfs-storage
            mountPath: /data
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: synology-nfs-pvc