apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system2
  name: solar-system-service2
spec:
  ports:
  - port: 80 #change to 80
    protocol: TCP
    targetPort: 80
  selector:
    app: solar-system2
  type: LoadBalancer