apiVersion: v1
data:
  policy.csv: |
    # Admin role
    p, role:admin, *, *, *, allow
    g, admin, role:admin

    # Partner role: full control only inside partner project
    p, role:partner, applications, get, partner-project/*, allow
    p, role:partner, applications, create, partner-project/*, allow
    p, role:partner, applications, update, partner-project/*, allow
    p, role:partner, applications, delete, partner-project/*, allow
    p, role:partner, applications, sync, partner-project/*, allow
    p, role:partner, logs, get, partner-project/*, allow
    p, role:partner, clusters, get, https://212.2.243.159:6443, allow
    g, partner, role:partner

    # DevOps role: full control only inside devOps project
    p, role:devops, applications, get, devops-project/*, allow
    p, role:devops, applications, create, devops-project/*, allow
    p, role:devops, applications, update, devops-project/*, allow
    p, role:devops, applications, delete, devops-project/*, allow
    p, role:devops, applications, sync, devops-project/*, allow
    p, role:devops, logs, get, devops-project/*, allow
    p, role:devops, clusters, get, https://kubernetes.default.svc, allow
    g, devops, role:devops

    # Go to AD check detail of each user, need to ensure email,
    # displayname present or account won't work
    # Edited to here by Norman via ChatGPT

  policy.default: role:none
  scopes: '[groups]'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2026-02-24T04:47:19Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.3.2
    helm.sh/chart: argo-cd-9.4.4
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "2323809"
  uid: eac1cf17-01d9-4fb8-93a6-af2b316e5cf3
