apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multiple-sources
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  sources:
   - chart: ingress-nginx
     repoURL: "https://kubernetes.github.io/ingress-nginx"
     targetRevision: 4.6.1
     helm:
       valuesFiles:
         -$values/ingress-nginx/values.yaml
   - repoURL: "https://github.com/argoproj/argocd-example-apps.git"
     ref: values
     targetRevision: master
